# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(db_index=True, max_length=16)),
                ('last_login_date', models.DateTimeField()),
                ('display_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puppet.User'),
        ),
    ]
