# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('argument_allowed', models.BooleanField(default=False)),
                ('argument', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='hash',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 20, 29, 21, 846947, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='puppet_classes',
            field=models.ManyToManyField(to='puppet.PuppetClass'),
        ),
    ]
