# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0002_auto_20160318_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppetclass',
            name='argument',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
