# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0004_auto_20160318_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='fqdn',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
