# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0005_host_fqdn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppetclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='host',
            name='fqdn',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='puppetclass',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginid',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
