# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0007_auto_20160321_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(),
        ),
    ]
