# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0009_user_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login_date',
            new_name='last_login',
        ),
    ]
