# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0010_auto_20160321_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
