# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 00:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import puppet.models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0015_auto_20160321_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hash',
            field=models.CharField(max_length=128, validators=[puppet.models.validate_hash, django.core.validators.MinLengthValidator(95)]),
        ),
    ]
