# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0016_auto_20160321_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='fqdn',
            field=models.CharField(max_length=255, unique=True, verbose_name=' FQDN'),
        ),
    ]
