# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0017_auto_20160322_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hash',
            field=models.CharField(max_length=128),
        ),
    ]
