# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0018_auto_20160323_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puppet.User'),
        ),
    ]
