# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0020_auto_20160324_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ou',
            field=models.CharField(max_length=200, verbose_name=' OU'),
        ),
    ]
