# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0021_auto_20160324_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppetclass',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='puppetclass',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='puppetclass',
            name='display_name',
            field=models.CharField(default='abc', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
