# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0023_auto_20160324_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppetclass',
            name='class_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
