# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import puppet.models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0024_auto_20160324_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='fqdn',
            field=models.CharField(max_length=255, unique=True, validators=[puppet.models.full_domain_validator], verbose_name=' FQDN'),
        ),
    ]
