# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0025_auto_20160405_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departmental_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
    ]
