# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import puppet.models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0026_auto_20160408_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterField(
            model_name='host',
            name='hash',
            field=models.CharField(max_length=128, validators=[puppet.models.validate_hash]),
        ),
    ]
